# Generated by Django 3.2.20 on 2023-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.BigIntegerField()),
                ('val2', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('val3', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
