# Generated by Django 3.2.20 on 2023-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mod1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.BigIntegerField()),
                ('l2', models.CharField(blank=True, max_length=255, null=True)),
                ('l3', models.BinaryField(blank=True, null=True)),
                ('llkkjhhhsdajvvasdbjouoiyewryusddcnvkvhfzdsdjhbkcdchdscgsd', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
